[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
retrosol_hangman = "4hvTWxjk5UPGhpVuF1tM9USHLgzKon2W2mrgfxitnEvs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
